### ISSUE TITLE
Incorrect information about the existence of Common Lisp

### ISSUE THREAD

**Issue by phoe** [pvik/pvik.github.io#1]
https://github.com/pvik/pvik.github.io/blob/dfe4e52cfec16c571dbf3fa87554afc90f225b8f/blog/clojure-to-common-lisp-part-1-getting-started/index.html#L118

> Common lisp is a set of specification and no language called common lisp itself exists.

I disagree. Common Lisp is a programming language standardized by ANSI under the name "ANSI INCITS 226-1994 American National Standard for Programming Language Common LISP".

Your argumentation is also fully applicable to [ANSI C](https://en.wikipedia.org/wiki/ANSI_C) that is implemented by GCC, Clang, MSVC, and other C compilers, but I do not think that saying "no language called C exists" is going to hold up anywhere.

**Comment by pvik** [comment]
Thanks for pointing out my mistake!

I have updated that sentence to reflect this now.

**Comment by phoe** [comment]
Thanks!
